import React, { useState, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { Button } from '@clipgrab/ui';
import { Link2, KeyRound, CheckCircle2 } from 'lucide-react';
import { PairingPayload } from '@clipgrab/types';

function Popup() {
  const [paired, setPaired] = useState(false);
  const [pairingPayload, setPairingPayload] = useState('');
  const [errorMsg, setErrorMsg] = useState('');

  useEffect(() => {
    if (typeof chrome !== 'undefined' && chrome.storage) {
      chrome.storage.local.get('clipgrab_pairing_key', (result) => {
        if (result.clipgrab_pairing_key) {
          setPaired(true);
        }
      });
    }
  }, []);

  const handleSavePairingKey = () => {
    setErrorMsg('');
    try {
      const jsonStr = atob(pairingPayload.trim());
      const parsed: PairingPayload = JSON.parse(jsonStr);
      if (!parsed.databaseUrl || !parsed.passId) {
        throw new Error('Invalid payload fields');
      }

      if (typeof chrome !== 'undefined' && chrome.storage) {
        chrome.storage.local.set({ clipgrab_pairing_key: pairingPayload.trim() }, () => {
          setPaired(true);
        });
      } else {
        setPaired(true);
      }
    } catch (err: any) {
      setErrorMsg('Invalid Base64 pairing key format. Copy from Desktop Command Center.');
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center space-x-2">
        <Link2 className="w-5 h-5 text-indigo-400" />
        <h1 className="font-bold text-sm text-slate-100">ClipGrab Web Extension</h1>
      </div>

      {!paired ? (
        <div className="space-y-3">
          <p className="text-xs text-slate-400">
            Paste the Base64 pairing key generated by your Tauri Desktop Command Center:
          </p>
          <input
            type="password"
            value={pairingPayload}
            onChange={(e) => setPairingPayload(e.target.value)}
            placeholder="eyJkYXRhYmFzZVVybCI6..."
            className="w-full text-xs p-2 rounded bg-slate-900 border border-slate-800 focus:outline-none focus:border-indigo-500 text-slate-100"
          />
          {errorMsg && <p className="text-xs text-rose-400">{errorMsg}</p>}
          <Button variant="primary" size="sm" className="w-full" onClick={handleSavePairingKey}>
            <KeyRound className="w-3 h-3 mr-1" /> Save Pairing Key
          </Button>
        </div>
      ) : (
        <div className="space-y-3">
          <div className="p-3 rounded-lg bg-emerald-950/60 border border-emerald-800/60 text-emerald-300 text-xs flex items-center space-x-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
            <span>Paired to Neon DB</span>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Right-click any link or video on YouTube, X, TikTok, or Instagram to send it directly to your Mac download queue.
          </p>
        </div>
      )}
    </div>
  );
}

const rootEl = document.getElementById('popup-root');
if (rootEl) {
  ReactDOM.createRoot(rootEl).render(
    <React.StrictMode>
      <Popup />
    </React.StrictMode>
  );
}
